services:
  arangodb:
    image: arangodb:3.11
    container_name: servelogic_app_arangodb
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: root
    volumes:
      - servelogic-app_arangodb_data:/var/lib/arangodb3

volumes:
  servelogic-app_arangodb_data:
